# Generated by Django 4.2.4 on 2023-09-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OlympTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("personal_recommend", models.JSONField(default=None, null=True)),
                (
                    "recommend",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "BUY"), (2, "SELL"), (3, "NEUTRAL")],
                        null=True,
                    ),
                ),
                (
                    "recommend_buy",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "recommend_sell",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "recommend_neutral",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("price", models.IntegerField(blank=True, default=1, null=True)),
                ("timing", models.IntegerField(blank=True, default=60, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[(1, "up"), (2, "down")],
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["asset", "created_at"],
                        name="tradingasse_asset_9e2159_idx",
                    ),
                    models.Index(fields=["asset"], name="tradingasse_asset_ea6f29_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovingAvg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommend",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "BUY"), (2, "SELL"), (3, "NEUTRAL")],
                        null=True,
                    ),
                ),
                (
                    "recommend_buy",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "recommend_sell",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("all_mvavg", models.JSONField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "olymptrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moving_olymp_trade",
                        to="tradingasset.olymptrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Indicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open", models.FloatField(default=0.0)),
                ("close", models.FloatField(default=0.0)),
                ("low", models.FloatField(default=0.0)),
                ("high", models.FloatField(default=0.0)),
                ("indictors", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "olymptrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_olymp_trade",
                        to="tradingasset.olymptrade",
                    ),
                ),
            ],
        ),
    ]
