# Generated by Django 4.2.4 on 2023-09-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tradingasset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Osclillators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "BUY"), (2, "SELL"), (3, "NEUTRAL")],
                        null=True,
                    ),
                ),
                ("buy", models.IntegerField(blank=True, default=0, null=True)),
                ("sell", models.IntegerField(blank=True, default=0, null=True)),
                ("neutral", models.IntegerField(blank=True, default=0, null=True)),
                ("oscillators", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "olymptrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="osclillator_olymp_trade",
                        to="tradingasset.olymptrade",
                    ),
                ),
            ],
        ),
    ]
